import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { useAppDispatch, useAppSelector } from "~/store";
import { isAuthenticated } from "~/store/auth";

export default function Home() {
  const dispatch=useAppDispatch();
  const auth=useAppSelector((state)=>state.auth);
  const router=useRouter();
  useEffect(() => {
    if (auth.isAuthenticated === undefined) {
      dispatch(isAuthenticated());
    }else if (auth.isAuthenticated === true) {
      router.push("/prompt");
    }  
  }, [auth, dispatch, router]);
  return (
    <>
      <Head>
        <title>TrueFoundry Prompt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl text-black font-extrabold tracking-tight sm:text-[5rem]">
            TrueFoundry <span className="text-[hsl(280,100%,70%)]">Prompt</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 text-center">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/10 p-4 hover:bg-white/20 justify-center"
              href="/login"
            >
              <h3 className="text-2xl font-bold"> Sign In Now</h3>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-black/10 p-4 hover:bg-white/20"
              href="https://www.hiteshmodi.in"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">
                Learn more about <br/> the developer
              </h3>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
